# Config file for automatic testing at travis-ci.org
# This file will be regenerated if you run travis_pypi_setup.py

language: python
python: 3.5
dist: trusty

env:
  - TOXENV=py35
  - TOXENV=py34
  - TOXENV=py27
  - TOXENV=flake8

addons:
  apt:
    packages:
    - cmake
    - build-essential
    - libglib2.0-dev
    - bluez
    - bluetooth
    - python-dev
    - python3-dev
    - libbluetooth-dev
    - libboost-python-dev
    - libboost-thread-dev

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip install -U tox python-coveralls

# command to run tests, e.g. python setup.py test
script: tox -e ${TOXENV}

after_success:
  - coveralls

# After you create the Github repo and add it to Travis, run the
# travis_pypi_setup.py script to finish PyPI deployment setup
deploy:
  provider: pypi
  distributions: sdist
  user: hbldh
  password:
    secure: PLEASE_REPLACE_ME
  on:
    tags: true
    repo: hbldh/pymetawear
    condition: $TOXENV == py27
